### PR TITLE
Added Favorite Currency Feature and API upgrade

### PR DESCRIPTION
**Pull request by custardcream98**
* Added `Favorite Currency` feature discussed in [here](https://github.com/jeppestaerk/alfred-currency-conversion/issues/5)
curcon
 
* Added Input support for `₩`(KRW), `₽`(RUB), `₹`(INR)

### CODE REVIEW

**Comment by custardcream98** [comment]
Well, this will work fine for now!

**Comment by custardcream98** [comment]
I am currently fixing [this](https://github.com/custardcream98/alfred-currency-conversion/commit/bc39f6404bbb115b39d92fd13809636add10b4e8). Please use [this](https://github.com/custardcream98/alfred-currency-conversion/commit/73a4036395eab5c4508d2f0b1c13f0f3c4f9b491) instead.

**Comment by custardcream98** [comment]
[This commit](https://github.com/custardcream98/alfred-currency-conversion/commit/f2914bd2eaee0f9dd1eb108cfe01ba8a79d48d92) would be my last commit if there's no more feedback.
I've added `Remove` option of `Favorite Currency List`,
and I've changed `exchangerate-api v4` to `open.er-api v6` due to `WARNING_UPGRADE_TO_V6`  
  
curcon2

**Comment by jeppestaerk** [comment]
Nice work 👍

**Comment by jeppestaerk** [comment]
@custardcream98 could you update the readme also?

**Pull request merged**
